spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/newsfeed}
    username: ${SPRING_DATASOURCE_USERNAME:newsfeed}
    password: ${SPRING_DATASOURCE_PASSWORD:newsfeed}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        web: DEBUG
